#!/bin/bash

case $BLOCK_BUTTON in
	1) bin/connection-conn;;
	2) bin/connection-disc;;
    3) bin/connection-unit;;
	4) bin/connection-prev;;
	5) bin/connection-next;;	
    *) ;;
esac

echo "$(bin/connection-info)"
