#!/bin/bash

case $BLOCK_BUTTON in
	1) /home/jan/documents/code/statusbar-networkmanager/bin/connection-conn;;
	2) /home/jan/documents/code/statusbar-networkmanager/bin/connection-disc;;
    3) /home/jan/documents/code/statusbar-networkmanager/bin/connection-unit;;
	4) /home/jan/documents/code/statusbar-networkmanager/bin/connection-prev;;
	5) /home/jan/documents/code/statusbar-networkmanager/bin/connection-next;;	
    *) ;;
esac

echo "$(/home/jan/documents/code/statusbar-networkmanager/bin/connection-info)"
