#!/bin/bash

case $BLOCK_BUTTON in
	1) #exec ./connection-conn	#cal connet/disconnect
	3) #call unit
	4) exec connection-next		#call next nework
	5) exec connection-prev		#call prev network

echo "${connection-info}"
